name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      solution-file: ./src/S3.Integration.sln
    steps:
      - uses: actions/checkout@v2
      - name: Backend build and test
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore ${{env.solution-file}}
      - name: Test
        run: dotnet test ${{env.solution-file}} --no-restore --verbosity normal